// Code generated by goctl. DO NOT EDIT.
// Source: hello.proto

package helloservice

import (
	"context"

	"gin/go-zero/test-demo/server/rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	HelloRequest  = rpc.HelloRequest
	HelloResponse = rpc.HelloResponse

	HelloService interface {
		SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	}

	defaultHelloService struct {
		cli zrpc.Client
	}
)

func NewHelloService(cli zrpc.Client) HelloService {
	return &defaultHelloService{
		cli: cli,
	}
}

func (m *defaultHelloService) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	client := rpc.NewHelloServiceClient(m.cli.Conn())
	return client.SayHello(ctx, in, opts...)
}
