// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.1
// source: book.proto

package book

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"

	"gorm.io/driver/mysql"
	"gorm.io/gorm"

	"fmt"

	"gin/rpc/user"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookRes struct {
	state         protoimpl.MessageState `gorm:"-"`
	sizeCache     protoimpl.SizeCache `gorm:"-"`
	unknownFields protoimpl.UnknownFields `gorm:"-"`

	ID      int64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty" form:"bookID"`
	Title   string  `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty" form:"title" binding:"required"`
	Author  string  `protobuf:"bytes,3,opt,name=Author,proto3" json:"Author,omitempty" form:"author" binding:"required"`
	Price   float64 `protobuf:"fixed64,4,opt,name=Price,proto3" json:"Price,omitempty" form:"price" binding:"required"`
	Sales   int64   `protobuf:"varint,5,opt,name=Sales,proto3" json:"Sales,omitempty" form:"sales" binding:"required"`
	Stock   int64   `protobuf:"varint,6,opt,name=Stock,proto3" json:"Stock,omitempty" form:"stock" binding:"required"`
	ImgPath string  `protobuf:"bytes,7,opt,name=Img_path,json=ImgPath,proto3" json:"Img_path,omitempty" gorm:"column:img_path"`
	Err     string  `protobuf:"bytes,8,opt,name=Err,proto3" json:"Err,omitempty" gorm:"-"`
}

func (*BookRes) TableName() string {
	return "books"
}

func (x *BookRes) Reset() {
	*x = BookRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_book_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookRes) ProtoMessage() {}

func (x *BookRes) ProtoReflect() protoreflect.Message {
	mi := &file_book_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookRes.ProtoReflect.Descriptor instead.
func (*BookRes) Descriptor() ([]byte, []int) {
	return file_book_proto_rawDescGZIP(), []int{0}
}

func (x *BookRes) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *BookRes) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BookRes) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *BookRes) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BookRes) GetSales() int64 {
	if x != nil {
		return x.Sales
	}
	return 0
}

func (x *BookRes) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *BookRes) GetImgPath() string {
	if x != nil {
		return x.ImgPath
	}
	return ""
}

func (x *BookRes) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type BookReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *BookReq) Reset() {
	*x = BookReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_book_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookReq) ProtoMessage() {}

func (x *BookReq) ProtoReflect() protoreflect.Message {
	mi := &file_book_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookReq.ProtoReflect.Descriptor instead.
func (*BookReq) Descriptor() ([]byte, []int) {
	return file_book_proto_rawDescGZIP(), []int{1}
}

func (x *BookReq) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type PageRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Books      []*BookRes `protobuf:"bytes,1,rep,name=Books,proto3" json:"Books,omitempty"`
	PageNo     int64      `protobuf:"varint,2,opt,name=PageNo,proto3" json:"PageNo,omitempty"`
	PageSize   int64      `protobuf:"varint,3,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	TotalPages int64      `protobuf:"varint,4,opt,name=TotalPages,proto3" json:"TotalPages,omitempty"`
	TotalBooks int64      `protobuf:"varint,5,opt,name=TotalBooks,proto3" json:"TotalBooks,omitempty"`
	MaxPrice   float64    `protobuf:"fixed64,6,opt,name=MaxPrice,proto3" json:"MaxPrice,omitempty"`
	MinPrice   float64    `protobuf:"fixed64,7,opt,name=MinPrice,proto3" json:"MinPrice,omitempty"`
	UserName   string     `protobuf:"bytes,8,opt,name=UserName,proto3" json:"UserName,omitempty"`
}

func (page *PageRes) IsFirstPage() bool {
	if page.PageNo == 1 {
		return false
	} else {
		return true
	}
}

func (page *PageRes) IsLastPage() bool {
	if page.PageNo == page.TotalPages {
		return false
	} else {
		return true
	}
}

func (page *PageRes) PrePage() int64 {
	return page.PageNo - 1
}

func (page *PageRes) SubPage() int64 {
	return page.PageNo + 1
}

func (page *PageRes) Test() bool {
	if page.MaxPrice == 0 {
		return false
	} else {
		return true
	}
}

func (page *PageRes) IsRoot() bool {
	DB, err := gorm.Open(mysql.Open("root:Chen@123@tcp(localhost)/bookstore"), &gorm.Config{})
	if err != nil {
		fmt.Println("connect to mysql error:", err)
		return false
	}
	var res string
	DB.Model(&user.UserRes{}).Select("privilege").Where("name = ?", page.UserName).Find(&res)
	if res == "Y" {
		return true
	} else {
		return false
	}
}

func (x *PageRes) Reset() {
	*x = PageRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_book_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRes) ProtoMessage() {}

func (x *PageRes) ProtoReflect() protoreflect.Message {
	mi := &file_book_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRes.ProtoReflect.Descriptor instead.
func (*PageRes) Descriptor() ([]byte, []int) {
	return file_book_proto_rawDescGZIP(), []int{2}
}

func (x *PageRes) GetBooks() []*BookRes {
	if x != nil {
		return x.Books
	}
	return nil
}

func (x *PageRes) GetPageNo() int64 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *PageRes) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageRes) GetTotalPages() int64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *PageRes) GetTotalBooks() int64 {
	if x != nil {
		return x.TotalBooks
	}
	return 0
}

func (x *PageRes) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *PageRes) GetMinPrice() float64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *PageRes) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type PageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxPrice float64 `protobuf:"fixed64,1,opt,name=MaxPrice,proto3" json:"MaxPrice,omitempty"`
	MinPrice float64 `protobuf:"fixed64,2,opt,name=MinPrice,proto3" json:"MinPrice,omitempty"`
	PageNo   int64   `protobuf:"varint,3,opt,name=PageNo,proto3" json:"PageNo,omitempty"`
}

func (x *PageReq) Reset() {
	*x = PageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_book_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageReq) ProtoMessage() {}

func (x *PageReq) ProtoReflect() protoreflect.Message {
	mi := &file_book_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageReq.ProtoReflect.Descriptor instead.
func (*PageReq) Descriptor() ([]byte, []int) {
	return file_book_proto_rawDescGZIP(), []int{3}
}

func (x *PageReq) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *PageReq) GetMinPrice() float64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *PageReq) GetPageNo() int64 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

type Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *Res) Reset() {
	*x = Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_book_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Res) ProtoMessage() {}

func (x *Res) ProtoReflect() protoreflect.Message {
	mi := &file_book_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Res.ProtoReflect.Descriptor instead.
func (*Res) Descriptor() ([]byte, []int) {
	return file_book_proto_rawDescGZIP(), []int{4}
}

func (x *Res) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type Books struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Books []*BookRes `protobuf:"bytes,1,rep,name=Books,proto3" json:"Books,omitempty"`
}

func (x *Books) Reset() {
	*x = Books{}
	if protoimpl.UnsafeEnabled {
		mi := &file_book_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Books) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Books) ProtoMessage() {}

func (x *Books) ProtoReflect() protoreflect.Message {
	mi := &file_book_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Books.ProtoReflect.Descriptor instead.
func (*Books) Descriptor() ([]byte, []int) {
	return file_book_proto_rawDescGZIP(), []int{5}
}

func (x *Books) GetBooks() []*BookRes {
	if x != nil {
		return x.Books
	}
	return nil
}

var File_book_proto protoreflect.FileDescriptor

var file_book_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x62, 0x6f,
	0x6f, 0x6b, 0x22, 0xb6, 0x01, 0x0a, 0x07, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x14,
	0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x61, 0x6c, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x53, 0x61, 0x6c, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x63,
	0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x19,
	0x0a, 0x08, 0x49, 0x6d, 0x67, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x49, 0x6d, 0x67, 0x50, 0x61, 0x74, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x72, 0x72,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x45, 0x72, 0x72, 0x22, 0x19, 0x0a, 0x07, 0x42,
	0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x22, 0xf6, 0x01, 0x0a, 0x07, 0x50, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x73, 0x12, 0x23, 0x0a, 0x05, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73,
	0x52, 0x05, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x61, 0x67, 0x65, 0x4e,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x50, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x12,
	0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x4d,
	0x61, 0x78, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x4d,
	0x61, 0x78, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x69, 0x6e, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x4d, 0x69, 0x6e, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x59, 0x0a, 0x07, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x61,
	0x78, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x4d, 0x61,
	0x78, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x69, 0x6e, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x4d, 0x69, 0x6e, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x50, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x22, 0x1d, 0x0a, 0x03, 0x52, 0x65,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x2c, 0x0a, 0x05, 0x42, 0x6f, 0x6f,
	0x6b, 0x73, 0x12, 0x23, 0x0a, 0x05, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73,
	0x52, 0x05, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x32, 0xac, 0x02, 0x0a, 0x0b, 0x42, 0x6f, 0x6f, 0x6b,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x27, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x6f,
	0x6f, 0x6b, 0x12, 0x0d, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65,
	0x71, 0x1a, 0x0d, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73,
	0x12, 0x27, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x50, 0x61, 0x67, 0x65, 0x12, 0x0d, 0x2e, 0x62, 0x6f,
	0x6f, 0x6b, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x62, 0x6f, 0x6f,
	0x6b, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x07, 0x44, 0x65, 0x6c,
	0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x0d, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x42, 0x6f, 0x6f, 0x6b,
	0x52, 0x65, 0x71, 0x1a, 0x09, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x52, 0x65, 0x73, 0x12, 0x25,
	0x0a, 0x09, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x0d, 0x2e, 0x62, 0x6f,
	0x6f, 0x6b, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x1a, 0x09, 0x2e, 0x62, 0x6f, 0x6f,
	0x6b, 0x2e, 0x52, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x42, 0x6f, 0x6f, 0x6b,
	0x12, 0x0d, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x1a,
	0x09, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x52, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x0d, 0x47, 0x65,
	0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0d, 0x2e, 0x62, 0x6f,
	0x6f, 0x6b, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x1a, 0x0b, 0x2e, 0x62, 0x6f, 0x6f,
	0x6b, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x12, 0x2d, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42, 0x6f,
	0x6f, 0x6b, 0x42, 0x79, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x0d, 0x2e, 0x62, 0x6f, 0x6f,
	0x6b, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x1a, 0x0b, 0x2e, 0x62, 0x6f, 0x6f, 0x6b,
	0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x62, 0x6f, 0x6f, 0x6b,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_book_proto_rawDescOnce sync.Once
	file_book_proto_rawDescData = file_book_proto_rawDesc
)

func file_book_proto_rawDescGZIP() []byte {
	file_book_proto_rawDescOnce.Do(func() {
		file_book_proto_rawDescData = protoimpl.X.CompressGZIP(file_book_proto_rawDescData)
	})
	return file_book_proto_rawDescData
}

var file_book_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_book_proto_goTypes = []interface{}{
	(*BookRes)(nil), // 0: book.BookRes
	(*BookReq)(nil), // 1: book.BookReq
	(*PageRes)(nil), // 2: book.PageRes
	(*PageReq)(nil), // 3: book.PageReq
	(*Res)(nil),     // 4: book.Res
	(*Books)(nil),   // 5: book.Books
}
var file_book_proto_depIdxs = []int32{
	0, // 0: book.PageRes.Books:type_name -> book.BookRes
	0, // 1: book.Books.Books:type_name -> book.BookRes
	1, // 2: book.BookService.GetBook:input_type -> book.BookReq
	3, // 3: book.BookService.GetPage:input_type -> book.PageReq
	1, // 4: book.BookService.DelBook:input_type -> book.BookReq
	0, // 5: book.BookService.AlterBook:input_type -> book.BookRes
	0, // 6: book.BookService.AddBook:input_type -> book.BookRes
	0, // 7: book.BookService.GetBookByName:input_type -> book.BookRes
	0, // 8: book.BookService.GetBookByAuthor:input_type -> book.BookRes
	0, // 9: book.BookService.GetBook:output_type -> book.BookRes
	2, // 10: book.BookService.GetPage:output_type -> book.PageRes
	4, // 11: book.BookService.DelBook:output_type -> book.Res
	4, // 12: book.BookService.AlterBook:output_type -> book.Res
	4, // 13: book.BookService.AddBook:output_type -> book.Res
	5, // 14: book.BookService.GetBookByName:output_type -> book.Books
	5, // 15: book.BookService.GetBookByAuthor:output_type -> book.Books
	9, // [9:16] is the sub-list for method output_type
	2, // [2:9] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_book_proto_init() }
func file_book_proto_init() {
	if File_book_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_book_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_book_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_book_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_book_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_book_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_book_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Books); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_book_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_book_proto_goTypes,
		DependencyIndexes: file_book_proto_depIdxs,
		MessageInfos:      file_book_proto_msgTypes,
	}.Build()
	File_book_proto = out.File
	file_book_proto_rawDesc = nil
	file_book_proto_goTypes = nil
	file_book_proto_depIdxs = nil
}
