// Code generated by goctl. DO NOT EDIT.
// Source: hello.proto

package server

import (
	"context"

	"go-zero/test-demo/internal/logic"
	"go-zero/test-demo/internal/svc"
	"go-zero/test-demo/server/rpc"
)

type HelloServiceServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedHelloServiceServer
}

func NewHelloServiceServer(svcCtx *svc.ServiceContext) *HelloServiceServer {
	return &HelloServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *HelloServiceServer) SayHello(ctx context.Context, in *rpc.HelloRequest) (*rpc.HelloResponse, error) {
	l := logic.NewSayHelloLogic(ctx, s.svcCtx)
	return l.SayHello(in)
}
