// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	UserName string `form:"username"`
	Password string `form:"password"`
}

type Response struct {
	Message string `json:"message"`
}

type OrderReq struct {
	Id string `path:"id"`
}

type OrderReply struct {
	Id       string `json:"id"`
	Name     string `json:"name"`
	UserName string `json:"userName"`
}


type RegisterRequest struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Password string `json:"password"`
	Gender string `json:"gender"`
}

type RegisterResponse struct {
	Reply string `json:"reply"`
}