// Code generated by goctl. DO NOT EDIT.
package user

type LRequest struct {
	UserName string `form:"username"`
	Password string `form:"password"`
}

type LResponse struct {
	Message string `json:"message"`
}
